# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end


  platform :android do
    lane :generateScreenshots do
      gradle(
        task: 'assemble assembleAndroidTest'
      )

      apk_path = Dir.glob("../**/*-debug.apk").first
      test_apk_path = Dir.glob("../**/*-debug-androidTest.apk").first

      screengrab(
        app_package_name: 'io.github.mohamedisoliman.flow',
        app_apk_path: File.absolute_path(apk_path),
        tests_apk_path:  File.absolute_path(test_apk_path)
      )
    end
  end

end
